default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  password: pg_password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: contacts_development

test:
  <<: *default
  database: contacts_test
